version: "0.1"
log:
  level: 7 # reference to linux warning level
core:
  tradeInterval: 5   # second, time interval between trades
  channelLength: 100 # channel length for incoming request
grpc:
  listenIP: "0.0.0.0" # grpc listen address
  listenPort: "80"    # grpc listen port
